default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: trello_development
  host: localhost
  port: 5432
  username: rails_dev
  password: password

test:
  <<: *default
  database: trello_test
  host: localhost
  port: 5432
  username: rails_dev
  password: password

production:
  <<: *default
  database: trello_production
  username: trello
  password: <%= ENV['TRELLO_DATABASE_PASSWORD'] %>
