#!/bin/sh
if ! head -1 "$1" | grep -qE "^(feat|fix|ci|chore|docs|test|style|refactor|perf|build|revert)(\(.+?\))?: .{1,}$"; then
    echo "Aborting commit. See Commitizen"
    echo "Starting of commit should be one of (feat|fix|ci|chore|docs|test|style|refactor|perf|build|revert)" >&2
    echo "You can read more details about commit message formatting in DEVELOPMENT.md "
    echo "After staging use (git cz) in bash"
    exit 1
fi